version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
      - 25:25
      - 465:465
      - 993:993
      - 4190:4190
      - 389:389
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../data/traefik.yml:/traefik.yml:ro
      - ../data/acme.json:/acme.json
      - ../data/config.yml:/config.yml:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.entrypoints=http'
      - 'traefik.http.routers.traefik.rule=Host(`traefik-dashboard.wool.homes`)'
      - 'traefik.http.middlewares.traefik-auth.basicauth.users=evan:$$apr1$$kpFdWhXp$$R9/n4EDHpn/e5TNLMGPZd1'
      - 'traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https'
      - 'traefik.http.routers.traefik.middlewares=traefik-https-redirect'
      - 'traefik.http.routers.traefik-secure.entrypoints=https'
      - 'traefik.http.routers.traefik-secure.rule=Host(`traefik-dashboard.wool.homes`)'
      - 'traefik.http.routers.traefik-secure.middlewares=traefik-auth'
      - 'traefik.http.routers.traefik-secure.tls=true'
      - 'traefik.http.routers.traefik-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.traefik-secure.tls.domains[0].main=wool.homes'
      - 'traefik.http.routers.traefik-secure.tls.domains[0].sans=*.wool.homes'
      - 'traefik.http.routers.traefik-secure.service=api@internal'

networks:
  proxy:
    external: true
