hosts: "*"
become: true
tasks:
  - name: Disable dynamic MOTD over ssh
    pamd:
      name: sshd
      type: session
      control: optional
      module_path: pam_motd.so
      state: absent

  - name: remove ubuntu motd spam
        become: true
        file:
          path: "/etc/update-motd.d/{{ item }}"
          state: absent
        loop:
          - 00-header
          - 50-landscape-sysinfo
          - 85-fwupd
          - 88-esm-announce
          - 91-contract-ua-esm-status
          - 80-livepatch
          - 51-cloudguest
          - 95-hwe-eol
          - 10-help-text
          - 50-motd-news
        when: ansible_distribution == 'Ubuntu'

  - name: add cleaner motd
    template: src=../templates/motd dest=/etc/motd