- name: Install ZSH
  hosts: "*"
  become: yes
  tasks:
  - name: install zsh packages
    sudo: yes
    apt: pkg={{ item }} state=installed
    tags: [packages]
    with_items:
      - zsh
      - zsh-doc

  - name: Set zsh as default shell
    user: name=evan shell=/usr/bin/zsh
    sudo: yes