- name: Install Docker engine
  hosts: "*"
  become: true
  vars_files:
    - ../default.yml
  tasks:
  - name: install depdencies
    apt:
      name: 
       - ca-certificates 
       - curl 
       - gnupg 
       - lsb-release
      state: present
      update_cache: true
    become: true

  - name: add GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repository to apt
    apt_repository:
      filename: docker 
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: install docker engine
    apt:
      name: 
        - docker-ce 
        - docker-ce-cli 
        - containerd.io
        - docker-compose-plugin
      state: present
      update_cache: true
    become: true

  - name: test docker
    command: docker info
    become: true

  - name: add docker group
    group: 
      name: docker
      state: present

  - name: add edisting user '{{ create_user }}' to group docker
    user:
      name: '{{ create_user }}'
      groups: docker
      append: yes

  - name: start docker service on boot
    systemd:
      name: "{{ item }}"
      enabled: true
      masked: no
    with_items:
      - docker.service
      - containerd.service
